### ISSUE TITLE
Running get-TeamsUsage script generates a token related error

### ISSUE THREAD

**Issue by TomasCrha** [microsoft/FastTrack#100]
# Category
- [ ] Suggested sample, script, or tool
- [ ] Bug in existing sample, script, or tool
- [*] Question / Feedback

# Issue Details
After registering the application according to following guide:
Login to Portal.Azure.Com
Navigate to "Azure Active Directory" > "App Registrations"
Click "New Application Registration"
Give your application a friendly name, Select application type "native", and enter a redirect URL in the format "urn:foo" and click create
Click on the App > Required Permissions
Click Add and select the "Microsoft Graph" API
Grant the App the "Read All Usage Reports" permission
Record the Application ID and use that for ClientID parameter in this script

and running the script as suggested:
.\Get-TeamsUsage.ps1 -tenantName "contoso.onmicrosoft.com" -ClientID "{your app id}" -GroupsReport getOffice365GroupsActivityDetail -Period D7 -redirectUri "urn:foo"

I get following error:
Get-ADALAccessToken : AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.

Seems to me that the token wasnt generated at all - did I miss something during the app config?
Thank you for any hints,
Tomas

## Suggested Sample, Script, or Tool
Full error:
Get-ADALAccessToken : AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: 779c1917-647f-48ba-9afb-8af916059000
Correlation ID: 10e63320-d698-466d-a27d-877ff4a2ba42
Timestamp: 2021-06-11 10:23:26Z
At C:\Users\******\Desktop\Get-TeamsUsage.ps1:116 char:14
+     $token = Get-ADALAccessToken `
+              ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-ADALAccessToken

No token was created. Please review all parameters to ensure they are correct
### Expected / Desired Behavior
Expected behavior is for the script to run as described:)

### Observed Behavior
Error above

**Comment by dwhitney7** [comment]
Thanks for the feedback, I am looking into this. It appears at first glance this may be an issue with one of the dependencies this script has, and you likely are doing everything just fine on your end for the app registration at least to this point.

**Comment by TomasCrha** [comment]
thank you for your commentary, please let me know once you have any update

**Comment by TomasCrha** [comment]
hello, any update?

**Comment by dwhitney7** [comment]
Hello, thank you for your patience as I look into options here. Unfortunately it looks like it would be a significant change on the provided script side to address this error with the way this script is written on a community dependency module.

That said, there is a Teams usage report already available in the Teams admin center as documented here: https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-usage-report. Additionally there is a report in the M365 admin center that provides the exact same data as this script, as documented here: https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/office-365-groups-ww?view=o365-worldwide. Please take a look at both of these, and note that you can export both of these from the respective admin center views as well.

**Comment by TomasCrha** [comment]
Hello dwhitney7, thank you for your comment
I know there are reports like this, but what I need is to built some kind of automation on this report., I need to somehow run such report with powershell, and to work further with the results I get from it
Thats the point - I need to have automatically generated the last activity field

**Comment by dwhitney7** [comment]
I have updated the dependency module the script uses to address the authentication token issue. Please feel free to re-open if it does not work for you. Thanks for your patience!

**Comment by TomasCrha** [comment]
Hello dwhitney7, tank you for the update - just one additional question - where should I run the script? In Azure as a runbook? Or from a local server? since I can see that the script is referring to a certain variables/parameters within it
THank you

**Comment by dwhitney7** [comment]
The script is interactive (asks for credentials) so is expected to be run on a workstation/local server. It also installs a few PowerShell modules on the workstation if not present already.

**Comment by TomasCrha** [comment]
Hello dwhitney7, many thanks for your help so far. Do you think you can help me to configure the AZ app that the script is referring to, according to its permissions, redirect URI etc?
Input parameters the script is asking for are described like this:
.EXAMPLE
 .\TeamsUsageReport.ps1 `
    -TenantName "contoso.onmicrosoft.com" `
    -ClientID "afl724e4-5ac1-1b9c-be7c-917c95fq1w28" `
    -GroupsReport getOffice365GroupsActivityDetail `
    -Period D7 `
    -redirectUri "urn:foo"
    
 but I am not sure what permissions should I grant for the AZ app, and what redirect URI should I use
do you think you can share your app config that you use for the script with me?
Thank you very much

**Comment by TomasCrha** [comment]
Hello dwhitney7,
one more thing to ask - when I run the script, authenticate when asked to, provide admin consent for the related app (i tried with one that I configured earlier but not sure it is correct)
I end up with this:
Sign in 
Sorry, but we’re having trouble signing you in.
AADSTS500113: No reply address is registered for the application. 

Can you advise what reply address to put into the AZ app?
Thank you very much

**Comment by TomasCrha** [comment]
Hello dwhitney7, do you think you can share your AZ app config related to this script? thank you!
