### ISSUE TITLE
run step 1 only - Permissions export 

### ISSUE THREAD

**Issue by Mahinder007** [microsoft/FastTrack#25]
I'm looking to find a way to only run Step 1 to collect permissions and stop script after step 1 is completed.

**Comment by patrick-rodgers** [comment]
To which script are you referring?

**Comment by soyalejolopez** [comment]
Hey @mahinder007 - I think you're probably referring to the Find-MailboxDelegates script. If so, you can comment out Lines 1028 thru 1032 from Script Version: 05012019. This will only run step 1 and not proceed with Steps 2 and 3. 

Essentially these lines: 

`Write-LogEntry -LogName:$LogFile -LogEntryText "STEP 2 of 3: Analyze Delegates..." -ForegroundColor Yellow`
      
`Create-Batches -InputPermissionsFile $PermsOutputFile`  

`Write-LogEntry -LogName:$LogFile -LogEntryText "STEP 3 of 3: Create schedule..." -ForegroundColor Yellow`

`Create-MigrationSchedule -InputBatchesFile $BatchesFile`

**Comment by soyalejolopez** [comment]
@Mahinder007 - closing this one out. If you're still having issues let us know - happy to help.
