### ISSUE TITLE
Better Fork? 

### ISSUE THREAD

**Issue by JBines** [microsoft/FastTrack#29]
https://github.com/JBines/Get-RecipientPermissions.ps1/blob/master/Get-RecipientPermissions.ps1

You can consider using this. Does the same plus more.

**Comment by soyalejolopez** [comment]
Thank you @jbines for sharing. Always up for collaborating :) Assuming here you're referring to the script: Find-MailboxDelegates.ps1 ? Does your script also identify permission dependencies and batch those that are associated (spider web batching)?

**Comment by JBines** [comment]
It's a function so pipe it straight in :) 

no csv's required

**Comment by soyalejolopez** [comment]
Thanks @JBines , so this looks like an option for Step 1 which is to collect permissions. Step 2 is a key piece of this script which is to associate those with dependencies so that they get migrated in the same batch. Will test it out, thanks for sharing!

**Comment by JBines** [comment]
No worries I see what you are suggesting. I guess once you have an array with all the permissions you can write a compare object for your user comparison. I'll work on the doco for this its a good point. 

You might be interested in that I hit a issue with non English mailbox folder permissions as the root folders names change based on language having a look at the script you might be running into the same issue.

**Comment by soyalejolopez** [comment]
Sounds good, let us know if you can incorporate that and we could merge efforts. Regarding the non-English mailbox folder, yes, we had ran into that in the past, we do a check for it and if fail we pull using folder type for perf reasons.

**Comment by patrick-rodgers** [comment]
We certainly are open to contributions of either new scripts or improvements to existing scripts. We can't really redirect folks to other repos as we can't control what might be published there.

**Comment by soyalejolopez** [comment]
Given this, I think we can go ahead and close this one out. Currently the scripts are not a 1:1 mapping and have different purposes. @JBines If you have recommendations or want to submit a PR for the script to improve it, would be happy to review and merge. Cheers!

**Comment by JBines** [comment]
FYI - https://practical365.com/migration/preliminary-permission-clean-up-steps-for-a-successful-mailbox-migration/
