### ISSUE TITLE
Issues running a script

### ISSUE THREAD

**Issue by satyakatta29** [microsoft/FastTrack#30]
I am trying to run the FInd-MailboxDelegates.ps1 and seem to get issues running it in Exchange 2016 powershell. I do see that it applies to Exchange 2010 and 2013, but wanted to check if it works with Exchange 2016 as well??

The errors that I am getting are like below
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.

The '<' is reserver for future use.

https://github.com/Microsoft/FastTrack/tree/master/scripts/Find-MailboxDelegates

**Comment by soyalejolopez** [comment]
Hi @satyakatta29, we haven't tested the script against 2016. Your mileage may vary. Although from the errors that you are getting, those don't seem to be due to exchange version but rather powershell version. Do you have a screenshot? Or scrubbed script logs we could review?

**Comment by satyakatta29** [comment]
Hi @soyalejolopez 

Apologies for the delay. Sending you the screenshot now.

<img width="732" alt="Capture" src="https://user-images.githubusercontent.com/51346393/59247182-da147180-8c61-11e9-971d-08fef2f3f07e.PNG">

**Comment by satyakatta29** [comment]
Seem to be more like powershell or module side issue. Powershell version is 5.1 and the article says above 3 are supported.

**Comment by soyalejolopez** [comment]
@satyakatta29 - looks like a character issue, which I've seen when copying/pasting the script directly from Github page. Could you try re-downloading the script using the "raw" option when copying/pasting?

**Comment by soyalejolopez** [comment]
Hi @satyakatta29 - were you able to resolve the issue with the above suggestion?

**Comment by satyakatta29** [comment]
Hi @soyalejolopez - I have copied the raw and it is working now. Thanks a lot for your assistance and this script is the best.

Just a quick and simple one, although it did create the batches, I noticed the attached error when the script was running. Checking through the users, they were already migrated to O365. So not sure why the script picked them up and advised DB is missing??
<img width="949" alt="Capture" src="https://user-images.githubusercontent.com/51346393/59734183-b9689f00-9293-11e9-9aa7-bd8e834aa579.PNG">

**Comment by soyalejolopez** [comment]
Great, glad to hear! 

Regarding the other error thrown, were you also connected EXO? The script retrieves users that have a RecipientType = "UserMailbox" . If the user has been migrated that value should be "MailUser" .

**Comment by satyakatta29** [comment]
No I haven't connected to EXO. I ran the same again on another customer and
it came up good though. So not sure why it did only for this particular
customer and only for few mailboxes. Anyway in regards to the script not
working, that is resolved now. Thanks a lot for your help.

**Comment by soyalejolopez** [comment]
Sounds great, thanks @satyakatta29! Will close this one out, cheers!
