### ISSUE TITLE
Get-groupcustom is not working as expected in cross forest

### ISSUE THREAD

**Issue by mkalees1** [microsoft/FastTrack#38]
Thank you for reporting an issue, making a suggestion, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to respond. Thanks!

# Category
- [ ] Suggested sample, script, or tool
- [x] Bug in existing sample, script, or tool
- [x] Question / Feedback

# Instructions
*Delete this section after reading*
* All suggestions, questions and issues related to FastTrack OSS are welcome, please let us know what's on your mind.
* This is not a general support forum for FastTrack, questions should be related to an existing or proposed OSS contribution
* Remember to include sufficient details and context
* If you have multiple suggestions, questions, or bugs please submit them in seperate issues so we can track resolution
* Complete the section below that matches your need and delete the others
* Thank you for your feedback!

# Issue Details

## Suggested Sample, Script, or Tool

_Please described the sample, script or tool you think would be useful. Ensure you provide enough detail for us to understand and include the use case(s) covered. Samples, scripts, and tool should be generic and applicable to a wide range of customers._

### Expected / Desired Behavior
_Please describe the expected behavior._

### Observed Behavior
_Please describe the behavior that occured._

### Steps to Reproduce
_Please describe the steps to reproduce the bug in sufficient detail to allow testing._

## Question / Feedback

_Ask away! - but remember this isn't a general support forum for FastTrack. Questions should be related to the OSS projects._

**Comment by soyalejolopez** [comment]
Hey @mkalees1 it looks like this one was created by accident? We'll close this one out, but feel free to revisit if there are additional details on the issue you would like to report. thanks!
