### ISSUE TITLE
AccountResourceEnv switch not working

### ISSUE THREAD

**Issue by viniciusramosc** [microsoft/FastTrack#41]
# Category
- [ ] Suggested sample, script, or tool
- [X] Bug in existing sample, script, or tool
- [ ] Question / Feedback
# Issue Details

### Expected / Desired Behavior
The expected behavior is that when you use the AccountResourceEnv, Linked Accounts and accounts from other domains in the forest are still able to be retrieved according to the Get-RecipientCustom function and to the ReadME instructions.

### Observed Behavior
When using autocomplete to add the switches, the AccountResourceEnv switch doesn't come up automatically and even though it accepts if you manually write it down, it doesn't take it in account when the script is run. I got errors telling me that the recipients were not found even when they do exist in the forest. 

### Steps to Reproduce
Try adding the -AccountResourceEnv switch using AutoComplete (start writing it down and pressing tab afterwards).
Also, running the script for linked users using this switch to validate it's not working

**Comment by soyalejolopez** [comment]
Hi @viniciusramosc , the script should have generated a log. What error do you see both in the console and in the log?

**Comment by viniciusramosc** [comment]
[Errors-Script-FindMailboxDelegates.txt](https://github.com/microsoft/FastTrack/files/3536259/Errors-Script-FindMailboxDelegates.txt)

Hi @soyalejolopez , I've uploaded the output of the script and pasted a console error inside the TXT too.
Please, mind that I ran the script with the following line:
.\Find-MailboxDelegates.ps1 -InputMailboxesCSV .\filename.csv -FullAccess -SendOnBehalfTo -SendAs -Calendar -EnumerateGroups -AccountResourceEnv

If you take a closer look, the "Script parameters passed" line doesn't show the AccountResourceEnv switch.

Let me know if I can provide any further details.
Thanks!

**Comment by soyalejolopez** [comment]
Thank you @viniciusramosc - we pushed out an update. Please grab the latest script version and try again. Cheers

**Comment by patrick-rodgers** [comment]
Going to close this as there has been no update so assume things are resolved. Thanks!
