### ISSUE TITLE
ERROR=You cannot call a method on a null-valued expression.

### ISSUE THREAD

**Issue by hbuhrmanlll** [microsoft/FastTrack#60]
Thank you for reporting an issue, making a suggestion, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to respond. Thanks!

# Category
- [ ] Suggested sample, script, or tool
- [ ] Bug in existing sample, script, or tool
- [x] Question / Feedback

# Issue Details

When running this script against some shared mailboxes for permission gather, I get the following error:
4/6/2020 2:34 PM : Get Permissions for: SharedMailbox@emailaddress.com
4/6/2020 2:34 PM : MBX= SharedMailbox@emailaddress.com ERROR=You cannot call a method on a null-valued expression. POSITION=                                            $groupDomainName = $groupDomainName.domainid.tostring()
 At P:\Find-MailboxDelegates.ps1:325 char:45
+ ...               $groupDomainName = $groupDomainName.domainid.tostring()
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

## Suggested Sample, Script, or Tool

This is the command I'm running: 

.\Find-MailboxDelegates.ps1 -FullAccess -SendAs -SendOnBehalfTo -EnumerateGroups -InputMailboxesCSV P:\InputUsers.csv -ExcludeServiceAcctsCSV P:\ExcludeUsers.csv

**Comment by soyalejolopez** [comment]
Hi @hbuhrmanlll, a couple of quick questions: what version of powershell are you running? Exchange version? And are you running this from the exchange console or regular powershell console?

**Comment by hbuhrmanlll** [comment]
Version 3,  Exchange 2013 CU23, and I'm running from a remote powershell console with loaded exchange cmdlets.

**Comment by hbuhrmanlll** [comment]
I just ran the script on an actual Exchange Server, everything is working now.   Thanks.
