### ISSUE TITLE
Find Delegates in Office 365

### ISSUE THREAD

**Issue by PHARKETT** [microsoft/FastTrack#68]
Thank you for reporting an issue, making a suggestion, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to respond. Thanks!

# Category
- [x ] Suggested sample, script, or tool
- [ ] Bug in existing sample, script, or tool
- [ ] Question / Feedback

# Issue Details
We are migrating users between tenants and nedd to batch them so we do not break delegation
## Suggested Sample, Script, or Tool
Could you modify the FindMailboxDelegates.ps1 script to work on Office365 (EXO) to find delegates to mailboxes in the same way it does for on-premise exchange Hybrid?

I have tried to run connected to On-premises AD and Exchange Online PowerShell and it appears to work for Full Access SendAS and Sendonbehalve but not calendar

**Comment by soyalejolopez** [comment]
Thank you @PHARKETT for your suggestion. We're currently not looking at expanding the capability of the script, but you're more than welcome to modify it and adapt to your needs. Apologies it took this long to acknowledge your suggestion.
