### ISSUE TITLE
MS Teams MMS convert Skype meeting to Teams meeting

### ISSUE THREAD

**Issue by GuyLB** [microsoft/FastTrack#91]
Thank you for reporting an issue, making a suggestion, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to respond. Thanks!

# Category
- [ ] Suggested sample, script, or tool
- [x] Bug in existing sample, script, or tool
- [ ] Question / Feedback

### Expected / Desired Behavior
I’m following this approach to use the MMS.
https://github.com/microsoft/FastTrack/tree/master/samples/teams-upgrade-snippets

### Observed Behavior
I can’t get the ‘Start-CsExMeetingMigration’ to fire. It will not be recognized as a cmdlt. If i run the ‘Get-commands’ then it shows up, but it will not work at all.

### Steps to Reproduce
I deleted all installed Teams modules, reinstalled the latest version 2.0
Ran Powershell ISE and the normal version_
I can connect to the other Cs cmdlts witout problems.

**Comment by dwhitney7** [comment]
Thanks for the feedback. Let me look into this.

**Comment by dwhitney7** [comment]
Can you confirm what admin role(s) you have assigned to your account? Do you have just Teams service admin? If so, try adding the Skype for Business Online service admin role to your account, wait a little bit, and try connecting to PowerShell and running the MMS command again.

**Comment by GuyLB** [comment]
Hi,
Thanks for your fast feedback, you're absolutely right! Got assigned both admin roles now instead of only the Teams admin role, and now it works as intended.
